name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true
          cache-dependency-path: ./go.sum

      - name: Run Postgres
        run: |
          docker run --rm -d \
          --name postgres_test \
          -p 5432:5432 \
          -e POSTGRES_PASSWORD=password \
          -e POSTGRES_DB=gojwtauth \
          -v ${{ github.workspace }}/initdb:/docker-entrypoint-initdb.d \
          postgres

      - name: Run Test
        run: go test ./...
        env:
          SERVER_HOST: 0.0.0.0
          SERVER_PORT: 8000
          POSTGRES_TEST_HOST: localhost
          POSTGRES_TEST_PORT: 5432
          POSTGRES_TEST_USER: postgres
          POSTGRES_TEST_PASSWORD: password
          POSTGRES_TEST_DB: gojwtauth
          JWT_SECRET: b5a636fc-bd01-41b1-9780-7bbd906fa4c0
